version: '3.8'

services:
  denet-api:
      build: ./
      restart: unless-stopped
      command: ./denet-api
      ports:
        - 8080:8080
      depends_on:
        - database
      environment:
        - DB_PASSWORD=${DB_PASSWORD}


  database:
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: qwerty
    ports:
      - "5436:5432"
    volumes:
      - psql_volume:/var/lib/postgresql/data

  

volumes:
  psql_volume:
